import type { Metadata } from 'next';
import { MarketingNav } from '../../components/marketing-nav';
import { MarketingFooter } from '../../components/marketing-footer';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'NovaGate Privacy Policy. We never see your API request or response payloads. Learn exactly what we collect, how we use it, and your data rights.',
  openGraph: {
    title: 'NovaGate Privacy Policy',
    description: 'We never see your API payloads. Learn what telemetry we collect and how your data is protected.',
    url: 'https://novagate.dev/privacy',
  },
  alternates: { canonical: 'https://novagate.dev/privacy' },
};

const SECTIONS = [
  {
    title: '1. What We Collect',
    content: [
      'Account information: your name, email address, and hashed password when you register.',
      'Gateway telemetry: request metadata sent by your gateway node — method, path, status code, latency, request ID, and consumer ID. We do not collect request bodies, response bodies, query parameters, or any personally identifiable information from your API traffic.',
      'Usage metadata: which dashboard pages you visit, when routes and services are created or modified, and error events generated by your gateway.',
    ],
  },
  {
    title: '2. What We Do Not Collect',
    content: [
      'We never see your API request or response payloads. Your traffic flows directly between your clients and your downstream services through the gateway node running on your server.',
      'We do not collect full IP addresses in metric labels or log fields.',
      'We do not read your JWT tokens or API keys beyond validating their hashed form for authentication.',
    ],
  },
  {
    title: '3. How We Use Your Data',
    content: [
      'To provide the NovaGate service: authenticating your account, delivering config updates to your gateway, and displaying observability data in your dashboard.',
      'To improve the product: aggregate, anonymised usage patterns help us understand which features are used and where users encounter friction.',
      'We do not sell your data to third parties. We do not use your data for advertising.',
    ],
  },
  {
    title: '4. Data Storage and Retention',
    content: [
      'Account data is stored in PostgreSQL hosted in the EU (or region you select at registration).',
      'Request logs are retained for 7 days on the free plan. Enterprise plans may configure up to 90 days.',
      'Error events are retained for 30 days.',
      'Metrics snapshots are retained for 7 days (hourly), 30 days (daily).',
      'You can request full data export or deletion at any time by emailing privacy@novagate.dev.',
    ],
  },
  {
    title: '5. Security',
    content: [
      'All data in transit is encrypted with TLS 1.2 or higher.',
      'Passwords are hashed with bcrypt (cost factor 10) and never stored in plaintext.',
      'Database access requires authenticated connections. Tenant data is schema-isolated.',
      'See our Security page for a full account of our security practices.',
    ],
  },
  {
    title: '6. Third-Party Services',
    content: [
      'We use a transactional email provider (SMTP) to send password reset emails. Only your email address is shared with this provider.',
      'We do not use third-party analytics services, advertising platforms, or data brokers.',
    ],
  },
  {
    title: '7. Your Rights',
    content: [
      'You may request access to all data we hold about your account.',
      'You may request deletion of your account and all associated data.',
      'You may request correction of incorrect account information.',
      'To exercise these rights, email privacy@novagate.dev. We will respond within 30 days.',
    ],
  },
  {
    title: '8. Changes to This Policy',
    content: [
      'We will notify registered users by email at least 14 days before any material changes to this policy take effect.',
      'Continued use of the service after that date constitutes acceptance of the updated policy.',
    ],
  },
  {
    title: '9. Contact',
    content: [
      'Privacy-related requests: privacy@novagate.dev',
      'Security disclosures: security@novagate.dev',
      'General contact: hello@novagate.dev',
    ],
  },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#08080f] text-white">
      <MarketingNav />

      <div className="max-w-3xl mx-auto px-6 py-20">
        <div className="mb-12">
          <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-violet-500/50 mb-3">LEGAL</p>
          <h1 className="text-4xl font-black tracking-tight mb-3">Privacy Policy</h1>
          <p className="text-white/35 text-sm">Last updated: {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
          <p className="mt-4 text-white/45 text-sm leading-relaxed">
            This policy describes how NovaGate (&quot;we&quot;, &quot;our&quot;, &quot;us&quot;) collects, uses, and protects information when you use novagate.dev and the NovaGate gateway service.
          </p>
        </div>

        <div className="space-y-10">
          {SECTIONS.map((sec) => (
            <section key={sec.title}>
              <h2 className="text-lg font-bold text-white mb-4">{sec.title}</h2>
              <ul className="space-y-3">
                {sec.content.map((item, i) => (
                  <li key={i} className="flex items-start gap-3 text-sm text-white/45 leading-relaxed">
                    <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-violet-400/50" />
                    {item}
                  </li>
                ))}
              </ul>
            </section>
          ))}
        </div>
      </div>

      <MarketingFooter />
    </div>
  );
}
